### ISSUE TITLE
AG-UI support for nested events

### ISSUE THREAD

**Issue by NiuBlibing** [ag-ui-protocol/ag-ui#378]
In recent trends, multi-agent collaboration and parallel processing have become increasingly important for handling complex tasks. The current AG-UI design only supports sequential mode and lacks support for parallel events, which can lead to event confusion. 

<img width="1020" height="684" alt="Image" src="https://github.com/user-attachments/assets/1d199ca8-36e7-4baf-8e99-418014f5afa4" />

My preliminary idea is to add an `id` and `parent_id` to message, tool_call, and step events, allowing them to be associated across arbitrary hierarchical levels.

Similar issues: #174 #87

**Comment by tylerslaton** [comment]
#218 hi @NiuBlibing, this is solved by this issue. Going to try and get this moving forward again.

**Comment by NiuBlibing** [comment]
@tylerslaton In my opinion, PR #218  appears to only address the limitation of parallel output but does not resolve the hierarchical structure for event display. 

For example, in multi-agent scenarios, messages cannot be associated with their respective agents—each text or tool-call message lacks clear agent attribution. Additionally, step events often require nested, multi-level step structures.

**Comment by NathanTarbert** [comment]
@tylerslaton @mme, can you provide some insights to @NiuBlibing's comment.

 I'm going to add this to the roadmap for now.
