### ISSUE TITLE
[AG-UI-ADK] Missing `ToolCallResult` for `tool_context.actions.skip_summarization = True`

### ISSUE THREAD

**Issue by jamie0725** [ag-ui-protocol/ag-ui#765]
See this [issue](https://github.com/google/adk-python/issues/3748#issuecomment-3605933787)

I don't know if it is a bug on the ADK side or on the AG-UI side, so I am asking on both sides.

**Comment by jamie0725** [comment]
<img width="1424" height="506" alt="Image" src="https://github.com/user-attachments/assets/49e89f9b-77be-4b17-b671-92d92edcc78e" />

**Comment by jamie0725** [comment]
I found a fix:

In `async def _translate_text_content`

```python
...
            if is_duplicate:
                logger.info("⏭️ Skipping final response event (duplicate content detected from finished stream)")
            else:
                # Not a duplicate, or no previous stream. Send the full message.
                logger.info(f"⏩ Delivering complete non-streamed message or final content event_id={adk_event.id}")
                # -----FIX STARTS HERE: Only send message if there's actual content
                if combined_text:
                    message_events = [
                        TextMessageStartEvent(
                            type=EventType.TEXT_MESSAGE_START,
                            message_id=adk_event.id,  # Use event ID for non-streamed
                            role="assistant",
                        ),
                        TextMessageContentEvent(
                            type=EventType.TEXT_MESSAGE_CONTENT,
                            message_id=adk_event.id,
                            delta=combined_text,
                        ),
                        TextMessageEndEvent(
                            type=EventType.TEXT_MESSAGE_END,
                            message_id=adk_event.id,
                        ),
                    ]
                    for msg in message_events:
                        yield msg
                else:
                    logger.debug("Skipping empty text message in final response")
...
```

**Comment by contextablemark** [comment]
This issue should be addressed with https://github.com/ag-ui-protocol/ag-ui/pull/780. Please update to ag-ui-adk version 0.3.5 to pick up this change.

**Comment by jamie0725** [comment]
Unfortunatly it hasn't, the following error persists:
```
ERROR - Error translating ADK event: 1 validation error for TextMessageContentEvent
delta
  String should have at least 1 character [type=string_too_short, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.12/v/string_too_short
Traceback (most recent call last):
  File "/.venv/lib/python3.10/site-packages/ag_ui_adk/event_translator.py", line 181, in translate
    async for event in self._translate_text_content(
  File "/.venv/lib/python3.10/site-packages/ag_ui_adk/event_translator.py", line 336, in _translate_text_content
    TextMessageContentEvent(
  File "/.venv/lib/python3.10/site-packages/pydantic/main.py", line 250, in __init__
    validated_self = self.__pydantic_validator__.validate_python(data, self_instance=self)
pydantic_core._pydantic_core.ValidationError: 1 validation error for TextMessageContentEvent
delta
  String should have at least 1 character [type=string_too_short, input_value='', input_type=str]
    For further information visit https://errors.pydantic.dev/2.12/v/string_too_short
```
I think modifying the `event_translator.py` file is necessary, as described above.
```python
                # -----FIX STARTS HERE: Only send message if there's actual content
                if combined_text:
```

**Comment by jamie0725** [comment]
<img width="2152" height="1076" alt="Image" src="https://github.com/user-attachments/assets/20b07cf0-0bd0-4556-b110-8213fbf7be32" /> @contextablemark

**Comment by jamie0725** [comment]
https://github.com/ag-ui-protocol/ag-ui/pull/780/files#diff-2cf2e9e365519ce3cc22d0ffa9ddbe1f96a90309307117404a85d43826a0a4a0L339-L360

**Comment by bharlander** [comment]
Confirming same issue with 0.3.5. @jamie0725's fix did the trick.

**Comment by contextablemark** [comment]
@jamie0725 @bharlander A different approach, but this should do it.
